export const SET_CURRENT_RECTOR = "SET_CURRENT_RECTOR";
export const SET_CURRENT_VIDEO = "SET_CURRENT_VIDEO";

export const SEARCH_TEXT_IN_CURRENT_VIDEO = "SEARCH_TEXT_IN_CURRENT_VIDEO";

//Histories
export const SET_HISTORIES = "SET_HISTORIES";
export const SET_FILTRADES = "SET_FILTRADES";