//Rectors
export const SET_CURRENT_RECTOR = "SET_CURRENT_RECTOR";

//Vídeos
export const SET_CURRENT_VIDEO = "SET_CURRENT_VIDEO";

//Histories
export const INITIAL_HISTORIES = "INITIAL_HISTORIES";
export const SET_HISTORIES = "SET_HISTORIES";
export const SET_FILTRADES = "SET_FILTRADES";