export const SET_CURRENT_RECTOR = "SET_CURRENT_RECTOR";
export const SET_CURRENT_VIDEO = "SET_CURRENT_VIDEO";
export const SEARCH_TEXT = "SEARCH_TEXT";
export const SHOW_TEXT_RESULTS = "SHOW_TEXT_RESULTS";